server:
  port: 8001
  error:
    include-message: "always"
  shutdown: graceful

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  security:
    oauth2:
      client:
        registration:
          google:
            client_id: ${GOOGLE_CLIENT_ID}
            client_secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email, https://www.googleapis.com/auth/calendar.readonly
  datasource:
    url: jdbc:sqlite:file:../db.sqlite3
    driver-class-name: org.sqlite.JDBC