server:
  port: 8001
  error:
    include-message: "always"
  shutdown: graceful

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client_id: ${GOOGLE_CLIENT_ID}
            client_secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email, https://www.googleapis.com/auth/calendar.readonly