import org.springframework.boot.gradle.tasks.bundling.BootJar
import org.springframework.boot.gradle.tasks.run.BootRun

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("stream.pal.kotlin-common-conventions")
    // Spring plugins
    kotlin("plugin.spring")
    id("org.springframework.boot")
    id("io.spring.dependency-management")
}

dependencies {
    // Kotlin
    implementation("org.jetbrains.kotlin:kotlin-stdlib")
    // Kotlin coroutines
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")

    // Spring
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-aop")

    // Web jars
    implementation("org.webjars:jquery:3.7.0")
    implementation("org.webjars:bootstrap:5.3.1")
    implementation("org.webjars:webjars-locator:0.47")
}

tasks {
    // By default, we do not want sub-projects to generate a boot jar or boot run task.
    // Only the main app application will explicitly enable these tasks.
    getByName<BootJar>("bootJar") {
        enabled = false
    }
    getByName<BootRun>("bootRun") {
        enabled = false
    }
}