name: CI/CD pipeline 🚢

on:
  push:
    branches: [ main ]

concurrency:
  group: workflows-cicd

jobs:
  build-test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build and run tests
        run: make build
